app:
  datasource:
    jdbc-url: jdbc:postgresql://ec2-54-86-170-8.compute-1.amazonaws.com/d16u2nuhp45or4?sslmode=require
    username: navuinmwbnchhx
    password: f423d2d7ba6b695321942391366a55465c7dbbab1b972c08b4fd5ac67e6d8625
    pool-size: 30
